### ISSUE TITLE
Use io.swagger:*

### ISSUE THREAD

**Issue by davidkarlsen** [redlab/swagger-jaxb#7]
Swagger changed their groupId.
It's now in io.swagger:swagger-annotations:1.5.12
Could you switch to this version of the library - as it's what will be maintained.

**Comment by redlab** [comment]
I'll update it. I don't know if swagger-jaxb is still working thou. It has been a while since I checked it and used it.

**Comment by davidkarlsen** [comment]
Yes - it didn't seem very maintained, and I could not find any releases on central.
Are you aware of any similar jaxb-plugins?

**Comment by redlab** [comment]
No, I don't know any similar plugins. 

About maven central, that is correct, it has not been uploaded there. I decided the functionality was not enough and it was not fully finished. I did upload it at the private maven repo in the company I worked at that time and we used it for a short while.  

But now I'm even wondering if it is still needed to add swagger annotations to JAXB objects? I created this in the beginning since the field introspection did not work nicely. But now the swagger core docs states

>  swagger-core will introspect fields and setters/getters, it will also read and process JAXB annotations.

which makes this XJC plugin a bit useless?
